### ISSUE TITLE
公网部署问题

### ISSUE THREAD

**Issue by satan1a** [m0xiaoxi/AWD_CTF_Platform#1]
请问小西师傅，公网部署的话，怎么访问队伍自己的web服务呢？

**Comment by m0xiaoxi** [comment]
直接映射出来了，按端口访问就好，8801-880x

**Comment by satan1a** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    好的，谢谢小西师傅！
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                satan1a
                            
                    
                        
                            
                                    satan1a@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2019年07月31日 10:17，moxiaoxi<notifications@github.com> 写道： 


Closed #1.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
