### ISSUE TITLE
公网部署时，checker将所有服务器判定为宕机

### ISSUE THREAD

**Issue by SignorMercurio** [m0xiaoxi/AWD_CTF_Platform#14]
根据readme，运行：

```bash
python pre.py web_chinaz 3
python start.py 3
```

随后服务器防火墙打开了2201-2203，8801-8803以及9090端口，ssh能正常登录，web题页面也能正常访问，但checker判定所有服务器均宕机。手动运行了下checker得到结果如图：

![image](https://user-images.githubusercontent.com/32540679/68916425-df419380-07a0-11ea-9475-79273f98d717.png)

**Comment by Mitooooo** [comment]
web_chinaz check脚本的问题 手动把不好使的check删掉 重新部署就ok了
