### ISSUE TITLE
服务启动问题

### ISSUE THREAD

**Issue by satan1a** [m0xiaoxi/AWD_CTF_Platform#2]
服务器系统为ubuntu18.04, 在执行start.py脚本时，有如下错误：
[*] start docker team02
cp: cannot create regular file 'tmp/': Not a directory
cp: cannot create regular file 'tmp/': Not a directory
2f31376e7ed3b2c73e7eed7bb3a54c33882af86fbc1d26d6e89e314f5715c457
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/tmp/run.sh\": stat /tmp/run.sh: no such file or directory": unknown.
——————————
从而无法正常启动队伍的web环境，请问是否与docker.sh中以下命令有关：
cp run.sh tmp/
cp flag.py tmp/
请问该如何解决呢？

**Comment by m0xiaoxi** [comment]
直接解决就成了，少了tmp目录。上传了。
