### ISSUE TITLE
没有flag文件，第二轮也没有

### ISSUE THREAD

**Issue by Gu-f** [m0xiaoxi/AWD_CTF_Platform#25]
尝试了web_chinaz、web_example1都没有flag，等了好几轮都没有

**Comment by mo-xiaoxi** [comment]
给一下对应的测试环境和截图

**Comment by Gu-f** [comment]
谢谢您能给予回复。
测试环境如下：
公网阿里云、Ubuntu16.04LTS、宝塔、宝塔插件docker管理器2.2
所需公网端口已全部打开，防火墙开启从宝塔以及阿里云服务器管理后台打开的。
可正常访问docker环境，但是看不到flag文件。
当时没做截图，环境已删除，所以很抱歉无法提供截图。

最后结论：
放在本地虚拟机，不装宝塔可正常生成flag，因此猜测是公网防火墙或这是宝塔管理有拦截，但是无法定位到具体是什么进行的拦截。未测试在公网不装宝塔的情况下是否正常，如果确实是宝塔有拦截应该不装宝塔就能正常生成flag。按理来说宝塔应该不影响脚本往各个docker里面更新flag，因为同一个系统下应该算是内网访问，不应该有这种拦截。所以希望作者能尝试测试下，看看问题出在哪。以上是我猜测内容，不一定准确。谢谢。

**Comment by mo-xiaoxi** [comment]
好吧，没用过宝塔系统，这应该不属于这个仓库的问题orz
