### ISSUE TITLE
checker判定某队伍的服务Down后，该队伍的分数会回归初始值

### ISSUE THREAD

**Issue by meizjm3i** [m0xiaoxi/AWD_CTF_Platform#4]
# 服务器信息

Ubuntu 16.04

# 启动命令

python pre.py web_simplecms 3
python start.py 3

# 问题描述

当checker判定服务正常时，得失分的计算能正常进行。
当checker判定某队伍的服务down后，不论该队伍当前分数为多少，都会变为初始分数减去down的分数（默认设置下初始值是10000分，扣除down的分数为9900）。

**Comment by m0xiaoxi** [comment]
已修复
