### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by kevien** [m0xiaoxi/AWD_CTF_Platform#5]
作者您好，为啥check flag的时候 总是提示  flag错误 。。。

**Comment by m0xiaoxi** [comment]
给一下详细运行截图

**Comment by kevien** [comment]
![image](https://user-images.githubusercontent.com/3909737/64468426-1c612800-d157-11e9-92d5-8ceffab31317.png)

**Comment by kevien** [comment]
![image](https://user-images.githubusercontent.com/3909737/64468432-23883600-d157-11e9-94be-73d4fe715213.png)

**Comment by kevien** [comment]
![image](https://user-images.githubusercontent.com/3909737/64468433-2daa3480-d157-11e9-9a71-343ed2b7ce5f.png)

**Comment by kevien** [comment]
![image](https://user-images.githubusercontent.com/3909737/64468438-3dc21400-d157-11e9-8d13-536c982ffde0.png)

**Comment by m0xiaoxi** [comment]
已修复
