### ISSUE TITLE
Error response from daemon

### ISSUE THREAD

**Issue by 422926799** [m0xiaoxi/AWD_CTF_Platform#7]
Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/tmp/run.sh\": stat /tmp/run.sh: no such file or directory": unknown.

**Comment by Yanyouke** [comment]
权限问题

**Comment by 422926799** [comment]
> 权限问题

我全部给的777

**Comment by m0xiaoxi** [comment]
本地的run.sh没权限
