### ISSUE TITLE
运行时出现问题

### ISSUE THREAD

**Issue by deceasewolf** [m0xiaoxi/AWD_CTF_Platform#9]
错误信息：docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/tmp/run.sh\": permission denied": unknown.

**Comment by m0xiaoxi** [comment]
自己加一下权限

**Comment by deceasewolf** [comment]
> 自己加一下权限

我给整个文件夹加了777权限，执行以后还是出现这个问题，而且访问8801端口也是提示拒绝
